@echo off

REM Loading paths from config.ini...
for /f "tokens=1,2 delims==" %%a in (config.ini) do (
    if "%%a"=="ARCSearchEngineAlgorithmModule" set ARCSearchEngineAlgorithmModule=%%b
    if "%%a"=="ARCSearchEngineBackend" set ARCSearchEngineBackend=%%b
    if "%%a"=="Redis" set Redis=%%b
    if "%%a"=="ARCSearchEngineFrontend" set ARCSearchEngineFrontend=%%b
)

REM Starting Python algorithm Tornado service...
echo Starting Python algorithm Tornado service...
start "Python Algorithm Tornado Service" /d "%ARCSearchEngineAlgorithmModule%" /b "start.bat"

REM Starting backend service...
echo Starting backend service...
start "Backend Service" /d "%ARCSearchEngineBackend%" /b "start.bat"

REM Starting Redis service...
echo Starting Redis service...
start "Redis Service" /d "%Redis%" /b "redis-server.exe"

REM Starting frontend service...
echo Starting frontend service...
start "Frontend Service" /d "%ARCSearchEngineFrontend%" /b "start.bat"

echo All services started successfully!